### PR TITLE
Formatting cleanup, handle missing max file size in config, and update readme

### PR DESCRIPTION
**Pull request by ekuns**
Not a lot of changes here.  Mostly minor formatting updates, but also better handling of max file size if missing in the configuration file (have a default) and update the readme.

### CODE REVIEW

**Comment by ekuns** [comment]
Hmm, looks like a lot more faux changes got included in the request.  Hopefully it'll merge cleanly.  It should.  I updated my fork before I made any changes.

**Comment by Woody2143** [comment]
Yeah, it's pulling in those other commits I got rid of. Basically I think the old repo would need blown out and cloned again since I messed up.

If you wouldn't mind, could you make a copy of the file with your changes then delete & reclone, then copy the file back, commit and push.

**Comment by Woody2143** [comment]
Or I could squash and merge... That might work better.

**Comment by ekuns** [comment]
I'm happy either way.  Let me know which path you want to try first.

**Pull request merged**
